[build]
  command = "npm run build:ci"
  publish = "build"

[context.production]
  environment = { 
    CI = "false",
    NODE_VERSION = "18"
  }

[[plugins]]
  package = "@netlify/plugin-gatsby-cache"
